sudo: false
dist: trusty
language: c

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update
  - sudo apt-get install -y gcc-arm-embedded cmake
  - bash ./.travis/get-toolchain.sh

env:
 - TARGET_PLATFORM=nucleo-f429zi
 - TARGET_PLATFORM=unix
 - TARGET_PLATFORM=raspberrypi

script:
  - bash ./.travis/platform-build.sh
